""" pendin state

Revision ID: 02ac5cd25f37
Revises: d824468f44c2
Create Date: 2024-11-15 18:07:05.137257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02ac5cd25f37'
down_revision = 'd824468f44c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Pending', 'Completed', 'Cancelled', 'Processing', name='transactionstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('Pending', 'Completed', 'Cancelled', 'Processing', name='transactionstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###
