"""Add indexes to models 

Revision ID: 3af23d63276a
Revises: 57775a20108f
Create Date: 2024-11-18 20:26:22.097418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af23d63276a'
down_revision = '57775a20108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_locations', schema=None) as batch_op:
        batch_op.create_index('idx_lat_lon', ['latitude', 'longitude'], unique=False)

    with op.batch_alter_table('affected_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.create_index('idx_affected_area_lat_lon', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('idx_disease_count', ['disease_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affected_areas', schema=None) as batch_op:
        batch_op.drop_index('idx_disease_count')
        batch_op.drop_index('idx_affected_area_lat_lon')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('user_locations', schema=None) as batch_op:
        batch_op.drop_index('idx_lat_lon')

    op.drop_table('user_locations')
    # ### end Alembic commands ###
