"""Add Processing status to TransactionStatus

Revision ID: d824468f44c2
Revises: 6e52e55b00b7
Create Date: 2024-11-15 17:07:41.293708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd824468f44c2'
down_revision = '6e52e55b00b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'PROCESSING', name='transactionstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'PROCESSING', name='transactionstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
